from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "FILE_STRUCTURE_GRAPH.md"
IGNORE_NAMES = {".git", ".DS_Store", "__pycache__"}
NOTES = {
    "slides/": "HTML slide sources for presentations and visual summaries.",
    "scripts/": "Utility scripts, including structure graph generation.",
    "markdown-guide.md": "Introductory and reference guide to Markdown.",
}


def visible_children(path: Path) -> list[Path]:
    items = []
    for child in sorted(path.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())):
        if child.name.startswith(".") or child.name in IGNORE_NAMES:
            continue
        items.append(child)
    return items


def format_node(path: Path, prefix: str = "") -> list[str]:
    lines: list[str] = []
    children = visible_children(path)
    for index, child in enumerate(children):
        connector = "`-- " if index == len(children) - 1 else "|-- "
        relative = child.relative_to(ROOT).as_posix()
        label = f"{child.name}/" if child.is_dir() else child.name
        note_key = relative + "/" if child.is_dir() else relative
        note = NOTES.get(note_key)
        suffix = f"  ({note})" if note else ""
        lines.append(f"{prefix}{connector}{label}{suffix}")
        if child.is_dir():
            extension = "    " if index == len(children) - 1 else "|   "
            lines.extend(format_node(child, prefix + extension))
    return lines


def main() -> None:
    lines = [
        "# File Structure Graph",
        "",
        "Generated by `scripts/update_file_structure_graph.py`.",
        "",
        "```text",
        "./",
        *format_node(ROOT),
        "```",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
