import type { AppUser } from "./users.js";
import type { Course, Enrollment } from "./courses.js";
import type { AttendanceRecord, AttendanceSession } from "./attendance.js";
import type { Homework, HomeworkSubmission } from "./homework.js";
import type { PlaygroundExercise, PlaygroundLanguage } from "./playgrounds.js";
import type { AiProviderCapability } from "./ai.js";

export const sharedSeed = {
  users: [
    {
      id: "u-student-001",
      role: "student",
      status: "active",
      fullName: "Li Wei",
      email: "li.wei@cwnu.edu.cn",
      studentNumber: "INTL-2025001",
      program: "Computer Science",
      nationality: "China",
    },
    {
      id: "u-teacher-001",
      role: "teacher",
      status: "active",
      fullName: "Maria Gomez",
      email: "maria.gomez@cwnu.edu.cn",
      staffNumber: "T-1024",
      title: "Lecturer",
    },
    {
      id: "u-student-002",
      role: "student",
      status: "active",
      fullName: "Amina Yusuf",
      email: "amina.yusuf@cwnu.edu.cn",
      studentNumber: "INTL-2025002",
      program: "Software Engineering",
      nationality: "Nigeria",
    },
    {
      id: "u-admin-001",
      role: "admin",
      status: "active",
      fullName: "Chen Rui",
      email: "chen.rui@cwnu.edu.cn",
      permissions: ["users:manage", "courses:manage", "reports:view"],
    },
  ] satisfies AppUser[],
  courses: [
    {
      id: "c-001",
      code: "CNU-ENG-101",
      title: "Academic English for International Students",
      status: "active",
      teacherId: "u-teacher-001",
      semester: "2026-Spring",
      credits: 2,
      capacity: 40,
      tags: ["language", "orientation"],
      createdAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "c-002",
      code: "CNU-CS-104",
      title: "Programming Basics",
      status: "active",
      teacherId: "u-teacher-001",
      semester: "2026-Spring",
      credits: 3,
      capacity: 36,
      tags: ["coding", "web", "beginners"],
      createdAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "c-003",
      code: "CNU-LAB-220",
      title: "Compiler Lab",
      status: "active",
      teacherId: "u-teacher-001",
      semester: "2026-Spring",
      credits: 2,
      capacity: 24,
      tags: ["lab", "playground", "practice"],
      createdAt: "2026-01-01T00:00:00.000Z",
      updatedAt: "2026-01-01T00:00:00.000Z",
    },
  ] satisfies Course[],
  enrollments: [
    {
      id: "e-001",
      courseId: "c-001",
      studentId: "u-student-001",
      enrolledAt: "2026-02-10T00:00:00.000Z",
      status: "active",
    },
    {
      id: "e-002",
      courseId: "c-002",
      studentId: "u-student-001",
      enrolledAt: "2026-02-10T00:00:00.000Z",
      status: "active",
    },
    {
      id: "e-003",
      courseId: "c-003",
      studentId: "u-student-002",
      enrolledAt: "2026-02-10T00:00:00.000Z",
      status: "active",
    },
  ] satisfies Enrollment[],
  attendanceSessions: [
    {
      id: "a-001",
      courseId: "c-001",
      title: "Week 1 check-in",
      startsAt: "2026-03-01T08:00:00.000Z",
      endsAt: "2026-03-01T08:30:00.000Z",
      checkInDeadline: "2026-03-01T08:15:00.000Z",
      isOpen: false,
      createdBy: "u-teacher-001",
    },
    {
      id: "a-002",
      courseId: "c-002",
      title: "HTML and CSS Lab",
      startsAt: "2026-03-02T10:00:00.000Z",
      endsAt: "2026-03-02T11:30:00.000Z",
      checkInDeadline: "2026-03-02T10:10:00.000Z",
      isOpen: true,
      createdBy: "u-teacher-001",
    },
  ] satisfies AttendanceSession[],
  attendanceRecords: [
    {
      id: "ar-001",
      sessionId: "a-001",
      courseId: "c-001",
      studentId: "u-student-001",
      status: "present",
      checkedInAt: "2026-03-01T08:04:00.000Z",
      source: "manual",
    },
    {
      id: "ar-002",
      sessionId: "a-002",
      courseId: "c-002",
      studentId: "u-student-002",
      status: "late",
      checkedInAt: "2026-03-02T10:08:00.000Z",
      note: "Traffic delay",
      source: "manual",
    },
  ] satisfies AttendanceRecord[],
  homework: [
    {
      id: "h-001",
      courseId: "c-001",
      title: "Introduce Yourself",
      description: "Write a short self-introduction paragraph.",
      status: "published",
      dueAt: "2026-03-07T23:59:59.000Z",
      publishedAt: "2026-03-01T00:00:00.000Z",
      maxScore: 10,
      createdBy: "u-teacher-001",
      createdAt: "2026-03-01T00:00:00.000Z",
      updatedAt: "2026-03-01T00:00:00.000Z",
    },
    {
      id: "h-002",
      courseId: "c-002",
      title: "HTML Landing Page",
      description: "Build a simple landing page with headings, lists, and a call to action.",
      status: "published",
      dueAt: "2026-03-09T23:59:59.000Z",
      publishedAt: "2026-03-03T00:00:00.000Z",
      maxScore: 20,
      createdBy: "u-teacher-001",
      createdAt: "2026-03-03T00:00:00.000Z",
      updatedAt: "2026-03-03T00:00:00.000Z",
    },
  ] satisfies Homework[],
  homeworkSubmissions: [
    {
      id: "hs-001",
      homeworkId: "h-001",
      studentId: "u-student-001",
      status: "submitted",
      content: "Hello, my name is Li Wei and I am studying Computer Science.",
      submittedAt: "2026-03-05T13:00:00.000Z",
    },
    {
      id: "hs-002",
      homeworkId: "h-002",
      studentId: "u-student-002",
      status: "draft",
      content: "<main><h1>Welcome to my page</h1></main>",
    },
  ] satisfies HomeworkSubmission[],
  playgroundLanguages: [
    {
      id: "lang-html",
      key: "html",
      displayName: "HTML",
      extension: ".html",
      runtimeLabel: "Browser preview",
      docsUrl: "https://developer.mozilla.org/en-US/docs/Web/HTML",
      starterCode: "<!doctype html>\n<html>\n  <body>\n    <h1>Hello CWNU</h1>\n  </body>\n</html>\n",
      learningTips: ["Start with structure", "Use semantic tags"],
    },
    {
      id: "lang-css",
      key: "css",
      displayName: "CSS",
      extension: ".css",
      runtimeLabel: "Browser preview",
      docsUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS",
      starterCode: "body {\n  font-family: sans-serif;\n}\n",
      learningTips: ["Think in layout systems", "Prefer reusable classes"],
    },
    {
      id: "lang-javascript",
      key: "javascript",
      displayName: "JavaScript",
      extension: ".js",
      runtimeLabel: "Browser runtime",
      docsUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
      starterCode: "console.log('Hello CWNU');\n",
      learningTips: ["Read the error message carefully", "Test one small change at a time"],
    },
    {
      id: "lang-cpp",
      key: "cpp",
      displayName: "C++",
      extension: ".cpp",
      runtimeLabel: "Sandbox compiler",
      compiler: "g++",
      docsUrl: "https://en.cppreference.com/w/",
      starterCode: "#include <iostream>\nint main() {\n  std::cout << \"Hello CWNU\\n\";\n}\n",
      learningTips: ["Remember semicolons", "Watch your includes"],
    },
    {
      id: "lang-java",
      key: "java",
      displayName: "Java",
      extension: ".java",
      runtimeLabel: "Sandbox compiler",
      compiler: "javac",
      docsUrl: "https://docs.oracle.com/en/java/",
      starterCode: "class Main {\n  public static void main(String[] args) {\n    System.out.println(\"Hello CWNU\");\n  }\n}\n",
      learningTips: ["Class name and file name must match", "Watch your braces"],
    },
    {
      id: "lang-kotlin",
      key: "kotlin",
      displayName: "Kotlin",
      extension: ".kt",
      runtimeLabel: "Sandbox compiler",
      compiler: "kotlinc",
      docsUrl: "https://kotlinlang.org/docs/home.html",
      starterCode: "fun main() {\n  println(\"Hello CWNU\")\n}\n",
      learningTips: ["Let type inference help you", "Null safety matters"],
    },
  ] satisfies PlaygroundLanguage[],
  playgroundExercises: [
    {
      id: "ex-html-001",
      languageId: "lang-html",
      title: "Build a profile card",
      prompt: "Create a simple student profile card with a heading and paragraph.",
      starterCode: "<div class=\"card\"></div>",
      solutionHints: ["Use a heading tag", "Add a short self introduction"],
      tags: ["html", "beginner"],
      difficulty: "beginner",
    },
    {
      id: "ex-js-001",
      languageId: "lang-javascript",
      title: "Fix a loop bug",
      prompt: "Print the numbers 1 to 5 and explain why the original loop failed.",
      starterCode: "for (let i = 1; i <= 5; i++) {\n  console.log(i);\n}\n",
      solutionHints: ["Check the loop condition", "Read the console output closely"],
      tags: ["javascript", "loops"],
      difficulty: "beginner",
    },
    {
      id: "ex-cpp-001",
      languageId: "lang-cpp",
      title: "Read and echo a name",
      prompt: "Read a name from stdin and print a greeting.",
      starterCode: "#include <iostream>\n#include <string>\nint main() {\n  std::string name;\n  std::getline(std::cin, name);\n  std::cout << \"Hello, \" << name << \"\\n\";\n}\n",
      solutionHints: ["Use getline for full names", "Output should end with a newline"],
      tags: ["cpp", "stdin"],
      difficulty: "intermediate",
    },
  ] satisfies PlaygroundExercise[],
  aiProviderCapabilities: [
    {
      provider: "deepseek",
      supportsCodeFixing: true,
      supportsTeachingHints: true,
      supportsMultilingual: true,
    },
    {
      provider: "openai",
      supportsCodeFixing: true,
      supportsTeachingHints: true,
      supportsMultilingual: true,
    },
    {
      provider: "local",
      supportsCodeFixing: false,
      supportsTeachingHints: true,
      supportsMultilingual: false,
    },
  ] satisfies AiProviderCapability[],
} as const;

export type SharedSeed = typeof sharedSeed;
