from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "FILE_STRUCTURE_GRAPH.md"

IGNORED_DIRS = {
    ".git",
    "node_modules",
    ".next",
    "dist",
    "coverage",
    "__pycache__",
}

IMPORTANT_FILES = {
    "package.json",
    "tsconfig.base.json",
    "README.md",
    "COORDINATION.md",
    "FILE_STRUCTURE_GRAPH.md",
}


def should_include(path: Path) -> bool:
    return path.name in IMPORTANT_FILES or path.suffix in {
        ".html",
        ".ts",
        ".tsx",
        ".js",
        ".json",
        ".md",
        ".py",
    }


def walk(path: Path, indent: int = 0) -> list[str]:
    lines: list[str] = []
    children = sorted(path.iterdir(), key=lambda entry: (entry.is_file(), entry.name.lower()))
    for child in children:
        if child.name in IGNORED_DIRS:
            continue
        prefix = "  " * indent + "- "
        if child.is_dir():
            lines.append(f"{prefix}{child.name}/")
            lines.extend(walk(child, indent + 1))
            continue
        if should_include(child):
            lines.append(f"{prefix}{child.name}")
    return lines


def main() -> None:
    lines = [
        "# File Structure Graph",
        "",
        "Generated by `scripts/update_file_structure_graph.py`.",
        "",
    ]
    lines.extend(walk(ROOT))
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
